### ISSUE TITLE
Groovy 3.0 NoSuchMethodError VariableScopeVisitor.prepareVisit

### ISSUE THREAD

**Issue by aibolit** [grails/gorm-hibernate5#176]
Attempting to use Gorm with Groovy 3.0.0 causes the following Stacktrace.

It looks like the `prepareVisit` method was removed from `VariableScopeVisitor` in Groovy 3.0.

```
Caused by: java.lang.NoSuchMethodError: org.codehaus.groovy.classgen.VariableScopeVisitor.prepareVisit(Lorg/codehaus/groovy/ast/ClassNode;)V
	at org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.moveOriginalCodeToNewMethod(AbstractMethodDecoratingTransformation.groovy:334)
	at org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.weaveNewMethod(AbstractMethodDecoratingTransformation.groovy:185)
```

**Comment by puneetbehl** [comment]
@aibolit  I think this has been fixed in Groovy 3.0.2.

**Comment by aibolit** [comment]
in groovy v3.0.2 we get a different error

```
Caused by: java.lang.NoSuchMethodError: org.codehaus.groovy.ast.tools.GeneralUtils.propX(Lorg/codehaus/groovy/ast/expr/Expression;Ljava/lang/String;)Lorg/codehaus/groovy/ast/expr/Expression;
	at org.grails.datastore.gorm.transactions.transform.TransactionalTransform.applyTransactionalAttributeSettings(TransactionalTransform.groovy:435)
	at org.grails.datastore.gorm.transactions.transform.TransactionalTransform.buildDelegatingMethodCall(TransactionalTransform.groovy:335)```

**Comment by puneetbehl** [comment]
The master branch works fine with Groovy 3.0.2, I have not tested thoroughly but at least the tests are okay.
